const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function historyChart(points,{label,color='#65baff',delta=false,id='history'}={}){
 if(!points.length)return '';
 const first=points[0],last=points.at(-1),values=points.map(p=>delta?p.value-first.value:p.value),min=Math.min(...values),max=Math.max(...values),pad=Math.max(3,(max-min)*.15),low=min>=0?Math.max(0,min-pad):min-pad,high=max+pad;
 const start=Date.parse(first.at),end=Date.parse(last.at),x=p=>start===end?450:110+(Date.parse(p.at)-start)/(end-start)*650,y=v=>205-(v-low)/(high-low)*160;
 const coords=points.map((p,i)=>`${x(p).toFixed(1)},${y(values[i]).toFixed(1)}`).join(' '),nf=new Intl.NumberFormat(undefined,{maximumFractionDigits:0});
 const tick=n=>delta?(n>=0?'+':'')+nf.format(Math.round(n)):nf.format(Math.round(n));
 const date=at=>new Date(at).toLocaleDateString(undefined,{month:'short',day:'numeric'});
 const ticks=Array.from({length:4},(_,i)=>low+(high-low)*i/3);
 return `<div class="history-plot"><div class="chart-axis-caption">${delta?'Change from first recorded might':'Recorded balance'}</div><svg class="history-chart" viewBox="0 0 800 255" role="img" aria-label="${esc(label)}"><title>${esc(label)}</title><defs><linearGradient id="${id}-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="${color}" stop-opacity=".17"/><stop offset="100%" stop-color="${color}" stop-opacity=".01"/></linearGradient></defs>${ticks.map(n=>`<line x1="110" x2="760" y1="${y(n)}" y2="${y(n)}" stroke="#40566b" stroke-opacity=".45" stroke-dasharray="3 6"/><text x="96" y="${y(n)+4}" text-anchor="end" fill="#9ab0c3" font-size="13">${tick(n)}</text>`).join('')}${points.length>1?`<polygon points="${x(first)},205 ${coords} ${x(last)},205" fill="url(#${id}-fill)"/><polyline points="${coords}" fill="none" stroke="${color}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>`:''}${points.map((p,i)=>`<circle cx="${x(p)}" cy="${y(values[i])}" r="${i===points.length-1?5:3}" fill="${color}" stroke="#152536" stroke-width="2"><title>${esc(new Date(p.at).toLocaleString())} · ${nf.format(p.value)}</title></circle>`).join('')}<text x="110" y="237" fill="#9ab0c3" font-size="13">${date(first.at)}</text>${end!==start?`<text x="760" y="237" text-anchor="end" fill="#9ab0c3" font-size="13">${date(last.at)}</text>`:''}</svg></div>`;
}
